# Generated by Django 3.2.7 on 2021-09-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
